name: transferLearning
channels:
  - conda-forge
dependencies:
  - python=3.7
  - scikit-learn==0.22.1
  - pip
  - matplotlib
  - numpy=1.16.4
  - pandas=0.25.1
  - pillow
  - pip:
    - ktrain==0.9.4
    - tensorflow
    - git+https://github.com/amaiya/eli5@tfkeras_0_10_1 # needed for explainer function
    